#%RAML 1.0 NamedExample
xmlEx:
  <?xml version="1.0"?>
    <employees>
      <emp>
        <id>758602</id>
        <name>Jyo</name>
        <designation>Program Analyst</designation>
        <domain>Java</domain>
      </emp>
    </employees>